### ISSUE TITLE
Reload leaderboard after upload

### ISSUE THREAD

**Issue by GreepTheSheep** [XertroV/tm-upload-map-to-nadeo#2]
I tried adding a function to reload leaderboard after upload ([from nbeerten's sample](https://github.com/nbeerten/tm-refresh-leaderboard/blob/main/src/main.as#L34-L38)), but still outputs "map is not uploaded".

Is there another way to reload leaderboard like that or it seems to be impossible?

**Comment by XertroV** [comment]
Implemented in https://github.com/XertroV/tm-upload-map-to-nadeo/commit/f0d65b84ba76a39492246daf30a392478a4cb649
